"""
Write a minimal ``space.par`` compatible with ``read_space_pars`` / Fortran.

Required keywords (see ``ConvertedPython_code/space_pars.py``):
``obs_sp_file``, ``GCOGlib``, ``fwhm``, ``wave_lims``.
"""

from __future__ import annotations

from pathlib import Path
from typing import Iterable, Tuple


def write_minimal_space_par(
    path: str | Path,
    *,
    obs_sp_file: str,
    gcoglib: str,
    fwhm: float,
    wave_lims: Iterable[Tuple[float, float]],
    sn_ratio: float | None = None,
    rv_ini: float = 0.0,
    error_est: bool = False,
    extra_lines: Iterable[str] | None = None,
) -> Path:
    """
    Write ``space.par`` with mandatory keys for SP_Ace.

    ``wave_lims`` is an iterable of (lambda_min, lambda_max) pairs in Angstrom.
    """
    path = Path(path)
    lines: list[str] = [
        "# Generated by fortran_tools.space_par_build.write_minimal_space_par",
        f"obs_sp_file   {obs_sp_file}",
        f"GCOGlib       {gcoglib.rstrip('/')}/",
        f"fwhm          {fwhm}",
    ]
    parts: list[str] = []
    for lo, hi in wave_lims:
        parts.extend([str(lo), str(hi)])
    lines.append("wave_lims     " + " ".join(parts))
    if sn_ratio is not None and sn_ratio >= 1.0:
        lines.append(f"sn_ratio      {sn_ratio}")
    if rv_ini != 0.0:
        lines.append(f"RV_ini        {rv_ini}")
    if error_est:
        lines.append("error_est")
    if extra_lines:
        lines.extend(extra_lines)

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path
